# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Dec 26 18:48:29 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class _EditFieldDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: _EditFieldDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_4 = wx.StaticText(self, -1, _("Name:"))
        self.tc_name = wx.TextCtrl(self, -1, "")
        self.label_5 = wx.StaticText(self, -1, _("Type:"))
        self.rb_type_text = wx.RadioButton(self, -1, _("text"), style=wx.RB_GROUP)
        self.rb_type_checkbox = wx.RadioButton(self, -1, _("checkbox"))
        self.rb_type_multiline = wx.RadioButton(self, -1, _("multiline"))
        self.rb_type_date = wx.RadioButton(self, -1, _("date"))
        self.label_6 = wx.StaticText(self, -1, _("Default"))
        self.tc_default = wx.TextCtrl(self, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: _EditFieldDlg.__set_properties
        self.SetTitle(_("Field"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: _EditFieldDlg.__do_layout
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 6, 6)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1.Add(self.label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.tc_name, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_13.Add(self.rb_type_text, 0, wx.RIGHT, 6)
        sizer_13.Add(self.rb_type_checkbox, 0, wx.RIGHT, 6)
        sizer_13.Add(self.rb_type_multiline, 0, wx.RIGHT, 6)
        sizer_13.Add(self.rb_type_date, 0, wx.RIGHT, 6)
        grid_sizer_1.Add(sizer_13, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.tc_default, 0, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_12.Add(grid_sizer_1, 1, wx.ALL|wx.EXPAND, 6)
        self.SetSizer(sizer_12)
        sizer_12.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class _EditFieldDlg


